# Generated by Django 4.2.5 on 2023-11-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=25)),
                ("phone", models.CharField(default="N/A", max_length=10)),
            ],
            options={
                "db_table": "Admin",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("phone", models.CharField(max_length=15)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("interest", models.DecimalField(decimal_places=2, max_digits=5)),
                ("proof", models.CharField(max_length=255)),
                ("address", models.TextField()),
                (
                    "loan_type",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("daily", "Daily")],
                        max_length=10,
                    ),
                ),
                ("next_due", models.IntegerField(default=0)),
                ("next_due_date", models.DateField()),
                ("tenure", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "Users",
            },
        ),
    ]
