# Generated by Django 4.2.5 on 2023-12-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="lastpaid",
            field=models.DateField(null=True),
        ),
    ]
